name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.PEM_KEY }}" > key.pem
        chmod 600 key.pem

    - name: SSH into EC2, pull latest code, and restart Nginx
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} << 'EOF'
          cd /var/www/html/abdullah
          git pull origin main
          sudo systemctl restart nginx
        EOF
